INSERT INTO tags  VALUES ("HTML", null);
INSERT INTO tags VALUES ("CSS", null);
INSERT INTO tags  VALUES ("Bootstrap", null);
INSERT INTO tags  VALUES ("Javascript", null);
INSERT INTO tags  VALUES ("Node", null);
INSERT INTO tags  VALUES ("Express", null);
INSERT INTO tags VALUES ("MySQL", null);
INSERT INTO tags  VALUES ("block elements", 1);
INSERT INTO tags VALUES ("classes", 2);
INSERT INTO tags  VALUES ("grid", 3);
INSERT INTO tags VALUES ("functions", 4);
INSERT INTO tag  VALUES ("npm packages", 5);
INSERT INTO tag  VALUES ("server", 6);
INSERT INTO tag VALUES ("joins", 7);